// Generated by scripts/gen-tokens.ts from ../design/fleet_dev.pen and design/scale.json. Do not edit: change the design and run `make tokens`.
export const fontSizes: readonly string[] = ['12', '13', '14', '15', '20', '28', '40']
export const radii: readonly string[] = ['4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '16']
export const shadows: readonly string[] = ['control', 'raised', 'float', 'popover', 'dialog', 'palette']
