import type { TokenSet } from './token-set.ts'

const quote = (font: string) => (/^[\w-]+$/.test(font) ? font : `"${font}"`)
const pxToRem = (v: string) => (v.endsWith('px') ? `${String(Number(v.slice(0, -2)) / 16)}rem` : v)

/** Prints the token set as Tailwind 4 `@theme` variables, plus dark values under `.dark`. */
export function writeCss(set: TokenSet, source: string): string {
  const theme = [
    '  --text-*: initial;',
    ...set.fontSizes.flatMap((f) => [`  --text-${f.name}: ${pxToRem(f.size)};`, `  --text-${f.name}--line-height: ${pxToRem(f.lineHeight)};`]),
    ...set.fontFamilies.map((f) => `  --font-${f.name}: ${f.stack.map(quote).join(', ')};`),
    ...set.colors.map((c) => `  --color-${c.name}: ${c.light};`),
    ...set.radii.map((r) => `  --radius-${r.name}: ${pxToRem(r.value)};`),
  ]
  const dark = set.colors.filter((c) => c.dark !== undefined).map((c) => `  --color-${c.name}: ${String(c.dark)};`)
  const layout = set.layout.map((l) => `  --layout-${l.name}: ${l.value};`)
  return [
    `/* Generated by scripts/gen-tokens.ts from ${source}. Do not edit: change the design and run \`make tokens\`. */`,
    '@theme static {', ...theme, '}', '',
    ':root {', ...layout, '}', '',
    ...(dark.length > 0 ? ['.dark {', ...dark, '}', ''] : []),
  ].join('\n')
}
