import type { TokenSet } from './token-set.ts'

const quote = (font: string) => (/^[\w-]+$/.test(font) ? font : `"${font}"`)
const pxToRem = (v: string) => (v.endsWith('px') ? `${String(Number(v.slice(0, -2)) / 16)}rem` : v)

/**
 * Prints the token set as Tailwind 4 `@theme` variables, plus dark values under `.dark`. The design owns
 * the type scale, and the radius and shadow scales when it defines them: Tailwind's defaults are removed,
 * so only the design's names exist (theme.css can alias shadcn's names onto them).
 */
export function writeCss(set: TokenSet, sources: string[]): string {
  const theme = [
    '  --text-*: initial;',
    ...set.fontSizes.flatMap((f) => [`  --text-${f.name}: ${pxToRem(f.size)};`, `  --text-${f.name}--line-height: ${pxToRem(f.lineHeight)};`]),
    ...set.fontFamilies.map((f) => `  --font-${f.name}: ${f.stack.map(quote).join(', ')};`),
    ...set.colors.map((c) => `  --color-${c.name}: ${c.light};`),
    ...(set.radii.length > 0 ? ['  --radius-*: initial;'] : []),
    ...set.radii.map((r) => `  --radius-${r.name}: ${pxToRem(r.value)};`),
    ...(set.shadows.length > 0 ? ['  --shadow-*: initial;'] : []),
    ...set.shadows.map((s) => `  --shadow-${s.name}: ${s.value};`),
  ]
  const dark = set.colors.filter((c) => c.dark !== undefined).map((c) => `  --color-${c.name}: ${String(c.dark)};`)
  const layout = set.layout.map((l) => `  --layout-${l.name}: ${l.value};`)
  return [
    `/* Generated by scripts/gen-tokens.ts from ${sources.join(' and ')}. Do not edit: change the design and run \`make tokens\`. */`,
    '@theme static {', ...theme, '}', '',
    ':root {', ...layout, '}', '',
    ...(dark.length > 0 ? ['.dark {', ...dark, '}', ''] : []),
  ].join('\n')
}

/** The design's size names, for `cn` (src/lib/utils.ts): it must know them to merge `text-13` with a colour. */
export function writeNames(set: TokenSet, sources: string[]): string {
  const list = (names: string[]) => `[${names.map((n) => `'${n}'`).join(', ')}]`
  return [
    `// Generated by scripts/gen-tokens.ts from ${sources.join(' and ')}. Do not edit: change the design and run \`make tokens\`.`,
    `export const fontSizes: readonly string[] = ${list(set.fontSizes.map((f) => f.name))}`,
    `export const radii: readonly string[] = ${list(set.radii.map((r) => r.name))}`,
    `export const shadows: readonly string[] = ${list(set.shadows.map((s) => s.name))}`,
    '',
  ].join('\n')
}
