"""Postgres schema for Agent Hub.

Source of truth for the database. Alembic migrations are generated from these
models and then reviewed by hand. Design notes: docs/DATA_MODEL.md.

Conventions
- UUID primary keys generated by Postgres (gen_random_uuid()).
- Enumerations are text columns with CHECK constraints (cheaper to change than
  Postgres enums).
- Every user-owned table has user_id. Children of sessions and messages use a
  composite foreign key (parent_id, user_id) so a row can never point at another
  user's parent.
- All timestamps are timestamptz.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    Computed,
    ForeignKey,
    ForeignKeyConstraint,
    Index,
    Integer,
    LargeBinary,
    SmallInteger,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY, TSVECTOR
from sqlalchemy.orm import Mapped, mapped_column

from app.core.db import Base


def one_of(column: str, values: tuple[str, ...], name: str | None = None) -> CheckConstraint:
    quoted = ", ".join(f"'{v}'" for v in values)
    return CheckConstraint(f"{column} IN ({quoted})", name=name or column)


def pk() -> Mapped[uuid.UUID]:
    return mapped_column(primary_key=True, server_default=text("gen_random_uuid()"))


def created_at() -> Mapped[datetime]:
    return mapped_column(server_default=func.now())


def updated_at() -> Mapped[datetime]:
    return mapped_column(server_default=func.now(), onupdate=func.now())


def user_fk() -> Mapped[uuid.UUID]:
    return mapped_column(ForeignKey("users.id", ondelete="CASCADE"))


AGENT_COLORS = ("red", "blue", "green", "purple", "amber", "grey")
AGENT_STAGES = ("beta", "stable")
AGENT_STATUSES = ("online", "degraded", "offline")
RUNTIME_TYPES = ("agentcore", "http")
AGENT_VISIBILITY = ("listed", "hidden")
TITLE_SOURCES = ("auto", "user")
MESSAGE_ROLES = ("user", "assistant")
MESSAGE_STATUSES = (
    "streaming",
    "awaiting_approval",
    "complete",
    "stopped",
    "failed",
    "interrupted",
)
OPEN_REPLY = "status IN ('streaming', 'awaiting_approval')"
FILE_PURPOSES = ("upload", "artifact", "thumbnail", "export", "tool_output")
FILE_STATUSES = ("pending", "uploaded", "failed")
TOOL_CALL_STATUSES = ("running", "awaiting_approval", "succeeded", "failed", "denied", "cancelled")
APPROVAL_STATUSES = ("pending", "approved", "denied", "expired", "cancelled")
ARTIFACT_TYPES = ("document", "code", "html", "table")
ARTIFACT_VERSION_STATUSES = ("streaming", "complete", "incomplete")


class Agent(Base):
    """The agent registry (D6). Global configuration, not user-owned."""

    __tablename__ = "agents"

    id: Mapped[uuid.UUID] = pk()
    slug: Mapped[str] = mapped_column(Text, unique=True)  # used in URLs: /agents/:slug
    name: Mapped[str] = mapped_column(Text)
    description: Mapped[str] = mapped_column(Text)
    tagline: Mapped[str | None] = mapped_column(Text)  # short description for the mobile catalog
    greeting: Mapped[str | None] = mapped_column(
        Text
    )  # new-session heading, e.g. "What are we building today?"
    icon: Mapped[str] = mapped_column(Text)  # lucide icon name
    color: Mapped[str] = mapped_column(Text)
    stage: Mapped[str] = mapped_column(Text, server_default="stable")
    status: Mapped[str] = mapped_column(Text, server_default="online")
    status_checked_at: Mapped[datetime | None]
    status_changed_at: Mapped[datetime | None]  # "Offline since …", "last seen …"
    visibility: Mapped[str] = mapped_column(Text, server_default="listed")
    runtime_type: Mapped[str] = mapped_column(Text)
    runtime_arn: Mapped[str | None] = mapped_column(Text)  # AgentCore runtime ARN
    runtime_qualifier: Mapped[str | None] = mapped_column(
        Text
    )  # AgentCore endpoint name, e.g. DEFAULT
    runtime_endpoint: Mapped[str | None] = mapped_column(Text)  # URL for runtime_type = http
    framework: Mapped[str | None] = mapped_column(Text)  # display only: strands, langgraph
    version: Mapped[str | None] = mapped_column(
        Text
    )  # deployed version, shown as "Agent updated to vN"
    deployed_at: Mapped[datetime | None]
    details: Mapped[dict[str, Any]] = mapped_column(
        server_default=text("'{}'::jsonb")
    )  # display only: model, region, framework version
    disclaimer: Mapped[str | None] = mapped_column(Text)
    capabilities: Mapped[dict[str, Any]] = mapped_column(server_default=text("'{}'::jsonb"))
    tools: Mapped[list[Any]] = mapped_column(server_default=text("'[]'::jsonb"))
    starters: Mapped[list[Any]] = mapped_column(server_default=text("'[]'::jsonb"))
    settings: Mapped[dict[str, Any]] = mapped_column(
        server_default=text("'{}'::jsonb")
    )  # history budget, run cap, memory
    sort_order: Mapped[int] = mapped_column(Integer, server_default="0")
    retired_at: Mapped[datetime | None]  # removed from the catalog; its sessions stay readable
    created_at: Mapped[datetime] = created_at()
    updated_at: Mapped[datetime] = updated_at()

    __table_args__ = (
        one_of("color", AGENT_COLORS),
        one_of("stage", AGENT_STAGES),
        one_of("status", AGENT_STATUSES),
        one_of("visibility", AGENT_VISIBILITY),
        one_of("runtime_type", RUNTIME_TYPES),
        CheckConstraint(
            "(runtime_type = 'agentcore' AND runtime_arn IS NOT NULL)"
            " OR (runtime_type = 'http' AND runtime_endpoint IS NOT NULL)",
            name="runtime_target",
        ),
    )


class Session(Base):
    """A conversation with one agent."""

    __tablename__ = "sessions"

    id: Mapped[uuid.UUID] = pk()
    user_id: Mapped[uuid.UUID] = user_fk()
    agent_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("agents.id", ondelete="RESTRICT"))
    title: Mapped[str | None] = mapped_column(Text)
    title_source: Mapped[str | None] = mapped_column(Text)
    last_message_at: Mapped[datetime] = mapped_column(server_default=func.now())
    pinned_at: Mapped[datetime | None]
    archived_at: Mapped[datetime | None]
    deleted_at: Mapped[datetime | None]  # soft delete for the undo window; purged afterwards
    created_at: Mapped[datetime] = created_at()
    updated_at: Mapped[datetime] = updated_at()

    __table_args__ = (
        one_of("title_source", TITLE_SOURCES),
        UniqueConstraint("id", "user_id"),  # target of composite foreign keys
        # Sidebar: one agent's live sessions, newest first.
        Index(
            "ix_sessions_sidebar",
            "user_id",
            "agent_id",
            text("last_message_at DESC"),
            postgresql_where=text("deleted_at IS NULL AND archived_at IS NULL"),
        ),
        # Catalog "continue where you left off" and ⌘K: live sessions across agents.
        Index(
            "ix_sessions_recent",
            "user_id",
            text("last_message_at DESC"),
            postgresql_where=text("deleted_at IS NULL"),
        ),
        Index(
            "ix_sessions_archived",
            "user_id",
            text("archived_at DESC"),
            postgresql_where=text("archived_at IS NOT NULL AND deleted_at IS NULL"),
        ),
        Index("ix_sessions_purge", "deleted_at", postgresql_where=text("deleted_at IS NOT NULL")),
        Index(None, "agent_id"),
    )


class Message(Base):
    """One turn. `blocks` is the ordered transcript content; side tables hold state (P6)."""

    __tablename__ = "messages"

    id: Mapped[uuid.UUID] = pk()
    session_id: Mapped[uuid.UUID]
    user_id: Mapped[uuid.UUID] = user_fk()
    seq: Mapped[int] = mapped_column(Integer)  # order within the session, assigned by the API
    role: Mapped[str] = mapped_column(Text)
    status: Mapped[str] = mapped_column(Text, server_default="complete")
    blocks: Mapped[list[Any]] = mapped_column(server_default=text("'[]'::jsonb"))
    client_message_id: Mapped[uuid.UUID | None]  # idempotent sends (user messages)
    reply_to_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("messages.id", ondelete="CASCADE")
    )
    agent_version: Mapped[str | None] = mapped_column(Text)  # agent version that produced the reply
    error: Mapped[dict[str, Any] | None]  # {code, message, retryable}
    usage: Mapped[dict[str, Any] | None]  # tokens, durations
    search_text: Mapped[str | None] = mapped_column(Text)  # plain text flattened from blocks
    search_vector: Mapped[str | None] = mapped_column(
        TSVECTOR, Computed("to_tsvector('english', coalesce(search_text, ''))", persisted=True)
    )
    started_at: Mapped[datetime | None]
    heartbeat_at: Mapped[
        datetime | None
    ]  # written by the task running the reply; a stale one means that task died
    cancel_requested_at: Mapped[
        datetime | None
    ]  # Stop; the running task checks it, whichever task received the request
    completed_at: Mapped[datetime | None]
    created_at: Mapped[datetime] = created_at()
    updated_at: Mapped[datetime] = updated_at()

    __table_args__ = (
        one_of("role", MESSAGE_ROLES),
        one_of("status", MESSAGE_STATUSES),
        CheckConstraint("jsonb_typeof(blocks) = 'array'", name="blocks_is_array"),
        CheckConstraint("role = 'assistant' OR status = 'complete'", name="user_message_complete"),
        ForeignKeyConstraint(
            ["session_id", "user_id"], ["sessions.id", "sessions.user_id"], ondelete="CASCADE"
        ),
        UniqueConstraint("id", "user_id"),
        # Reload a session in order; also enforces a unique order.
        UniqueConstraint("session_id", "seq"),
        # Per user, not per session: the first send creates the session, so a resend must find it (F03).
        UniqueConstraint("user_id", "client_message_id"),
        # One open reply per session: running or waiting for an approval (run_in_progress, ARCHITECTURE D19).
        Index(
            "uq_messages_open_reply_per_session",
            "session_id",
            unique=True,
            postgresql_where=text(OPEN_REPLY),
        ),
        Index("ix_messages_search", "search_vector", postgresql_using="gin"),
        Index(None, "reply_to_id"),
    )


class File(Base):
    """An object in S3 (D7): uploads, artifact bodies, thumbnails, exports."""

    __tablename__ = "files"

    id: Mapped[uuid.UUID] = pk()
    user_id: Mapped[uuid.UUID] = user_fk()
    session_id: Mapped[uuid.UUID | None]  # null while uploading before the first send (F03)
    message_id: Mapped[uuid.UUID | None]  # set when attached to a sent message
    purpose: Mapped[str] = mapped_column(Text)
    status: Mapped[str] = mapped_column(Text, server_default="pending")
    s3_key: Mapped[str] = mapped_column(Text, unique=True)
    filename: Mapped[str] = mapped_column(Text)
    content_type: Mapped[str] = mapped_column(Text)
    size_bytes: Mapped[int | None] = mapped_column(BigInteger)
    sha256: Mapped[bytes | None] = mapped_column(LargeBinary)
    uploaded_at: Mapped[datetime | None]
    created_at: Mapped[datetime] = created_at()

    __table_args__ = (
        one_of("purpose", FILE_PURPOSES),
        one_of("status", FILE_STATUSES),
        ForeignKeyConstraint(
            ["session_id", "user_id"], ["sessions.id", "sessions.user_id"], ondelete="CASCADE"
        ),
        ForeignKeyConstraint(
            ["message_id", "user_id"], ["messages.id", "messages.user_id"], ondelete="CASCADE"
        ),
        Index(None, "message_id"),
        Index(None, "session_id"),
        # Cleanup of uploads that never finished or were never sent.
        Index("ix_files_unattached", "created_at", postgresql_where=text("message_id IS NULL")),
    )


class ToolCall(Base):
    """A tool the agent ran, with timings and (truncated) input and output."""

    __tablename__ = "tool_calls"

    id: Mapped[uuid.UUID] = pk()
    message_id: Mapped[uuid.UUID]
    session_id: Mapped[uuid.UUID]
    user_id: Mapped[uuid.UUID] = user_fk()
    tool_use_id: Mapped[str] = mapped_column(Text)  # the agent's own id for the call
    name: Mapped[str] = mapped_column(Text)
    status: Mapped[str] = mapped_column(Text, server_default="running")
    summary: Mapped[str | None] = mapped_column(Text)
    input: Mapped[dict[str, Any] | None]
    output: Mapped[dict[str, Any] | None]
    output_file_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("files.id", ondelete="SET NULL")
    )
    started_at: Mapped[datetime] = mapped_column(server_default=func.now())
    completed_at: Mapped[datetime | None]

    __table_args__ = (
        one_of("status", TOOL_CALL_STATUSES),
        ForeignKeyConstraint(
            ["message_id", "user_id"], ["messages.id", "messages.user_id"], ondelete="CASCADE"
        ),
        ForeignKeyConstraint(
            ["session_id", "user_id"], ["sessions.id", "sessions.user_id"], ondelete="CASCADE"
        ),
        UniqueConstraint("message_id", "tool_use_id"),
        Index(None, "session_id"),
    )


class ApprovalRequest(Base):
    """A tool call waiting for the user's decision (F10). Also the audit record."""

    __tablename__ = "approval_requests"

    id: Mapped[uuid.UUID] = pk()
    tool_call_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("tool_calls.id", ondelete="CASCADE"), unique=True
    )
    message_id: Mapped[uuid.UUID]
    session_id: Mapped[uuid.UUID]
    user_id: Mapped[uuid.UUID] = user_fk()
    agent_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("agents.id", ondelete="RESTRICT"))
    tool_name: Mapped[str] = mapped_column(Text)
    arguments: Mapped[
        dict[str, Any]
    ]  # validated by the API; the card renders these, not model prose
    display: Mapped[dict[str, Any] | None]  # title, fields and note for the card
    status: Mapped[str] = mapped_column(Text, server_default="pending")
    expires_at: Mapped[datetime]
    decided_at: Mapped[datetime | None]
    decision_reason: Mapped[str | None] = mapped_column(
        Text
    )  # optional deny reason, sent to the agent
    decided_user_agent: Mapped[str | None] = mapped_column(Text)
    executed_at: Mapped[datetime | None]  # set when the backend runs the approved call
    created_at: Mapped[datetime] = created_at()

    __table_args__ = (
        one_of("status", APPROVAL_STATUSES),
        CheckConstraint(
            "(status IN ('pending', 'expired', 'cancelled')) = (decided_at IS NULL)",
            name="decided_at_matches",
        ),
        CheckConstraint("executed_at IS NULL OR status = 'approved'", name="execute_only_approved"),
        ForeignKeyConstraint(
            ["message_id", "user_id"], ["messages.id", "messages.user_id"], ondelete="CASCADE"
        ),
        ForeignKeyConstraint(
            ["session_id", "user_id"], ["sessions.id", "sessions.user_id"], ondelete="CASCADE"
        ),
        # Sidebar badge and "approval waiting in another session".
        Index(
            "ix_approvals_pending",
            "user_id",
            "session_id",
            postgresql_where=text("status = 'pending'"),
        ),
        # Expiry sweep.
        Index("ix_approvals_expiry", "expires_at", postgresql_where=text("status = 'pending'")),
    )


class Artifact(Base):
    """A document, code file, HTML app or table the agent produced, with versions (F09)."""

    __tablename__ = "artifacts"

    id: Mapped[uuid.UUID] = pk()
    session_id: Mapped[uuid.UUID]
    user_id: Mapped[uuid.UUID] = user_fk()
    created_message_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("messages.id", ondelete="SET NULL")
    )
    artifact_key: Mapped[str] = mapped_column(
        Text
    )  # the agent's id, so its later updates find the artifact
    type: Mapped[str] = mapped_column(Text)
    title: Mapped[str] = mapped_column(Text)
    language: Mapped[str | None] = mapped_column(Text)  # for code
    current_version: Mapped[int] = mapped_column(Integer, server_default="1")
    created_at: Mapped[datetime] = created_at()
    updated_at: Mapped[datetime] = updated_at()

    __table_args__ = (
        one_of("type", ARTIFACT_TYPES),
        ForeignKeyConstraint(
            ["session_id", "user_id"], ["sessions.id", "sessions.user_id"], ondelete="CASCADE"
        ),
        UniqueConstraint("session_id", "artifact_key"),
        # Artifacts library (P1): newest first, filter by type.
        Index("ix_artifacts_library", "user_id", text("updated_at DESC")),
        Index(None, "user_id", "type"),
    )


class ArtifactVersion(Base):
    """One version of an artifact. Small bodies inline, large ones in S3."""

    __tablename__ = "artifact_versions"

    id: Mapped[uuid.UUID] = pk()
    artifact_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("artifacts.id", ondelete="CASCADE"))
    user_id: Mapped[uuid.UUID] = user_fk()
    version: Mapped[int] = mapped_column(Integer)
    message_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("messages.id", ondelete="SET NULL")
    )
    status: Mapped[str] = mapped_column(Text, server_default="streaming")
    content: Mapped[str | None] = mapped_column(Text)
    file_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("files.id", ondelete="CASCADE"))
    thumbnail_file_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("files.id", ondelete="SET NULL")
    )
    content_type: Mapped[str | None] = mapped_column(
        Text
    )  # text/markdown, text/csv, text/html, ...
    size_bytes: Mapped[int | None] = mapped_column(BigInteger)
    change_note: Mapped[str | None] = mapped_column(Text)  # shown in the version menu
    created_at: Mapped[datetime] = created_at()

    __table_args__ = (
        one_of("status", ARTIFACT_VERSION_STATUSES),
        CheckConstraint(
            "status = 'streaming' OR content IS NOT NULL OR file_id IS NOT NULL", name="has_body"
        ),
        UniqueConstraint("artifact_id", "version"),
    )


class Feedback(Base):
    """Thumbs up or down on an assistant message, with reasons (F20)."""

    __tablename__ = "feedback"

    id: Mapped[uuid.UUID] = pk()
    message_id: Mapped[uuid.UUID]
    user_id: Mapped[uuid.UUID] = user_fk()
    rating: Mapped[int] = mapped_column(SmallInteger)
    reasons: Mapped[list[str]] = mapped_column(ARRAY(Text), server_default=text("'{}'::text[]"))
    comment: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = created_at()
    updated_at: Mapped[datetime] = updated_at()

    __table_args__ = (
        CheckConstraint("rating IN (-1, 1)", name="rating"),
        ForeignKeyConstraint(
            ["message_id", "user_id"], ["messages.id", "messages.user_id"], ondelete="CASCADE"
        ),
        UniqueConstraint("message_id", "user_id"),
        Index(None, "created_at"),  # eval export
    )


class ShareLink(Base):
    """A public, read-only link to a session as it was when shared (F18)."""

    __tablename__ = "share_links"

    id: Mapped[uuid.UUID] = pk()
    session_id: Mapped[uuid.UUID]
    user_id: Mapped[uuid.UUID] = user_fk()
    slug: Mapped[str] = mapped_column(Text, unique=True)  # random, unguessable: /s/:slug
    up_to_seq: Mapped[int] = mapped_column(Integer)  # snapshot boundary: messages with seq <= this
    view_count: Mapped[int] = mapped_column(Integer, server_default="0")
    last_viewed_at: Mapped[datetime | None]
    expires_at: Mapped[datetime | None]
    revoked_at: Mapped[datetime | None]
    created_at: Mapped[datetime] = created_at()

    __table_args__ = (
        ForeignKeyConstraint(
            ["session_id", "user_id"], ["sessions.id", "sessions.user_id"], ondelete="CASCADE"
        ),
        CheckConstraint("length(slug) >= 22", name="slug_length"),
        Index("ix_share_links_active", "session_id", postgresql_where=text("revoked_at IS NULL")),
    )
