"""initial schema
Generated by `alembic revision --autogenerate`, reviewed by hand. Tested upgrade, downgrade and `alembic check` on Postgres 17.

Revision ID: 0001
Revises: 
Create Date: 2026-09-29 13:28:41.436830
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=False),
    sa.Column('stage', sa.Text(), server_default='stable', nullable=False),
    sa.Column('status', sa.Text(), server_default='online', nullable=False),
    sa.Column('status_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visibility', sa.Text(), server_default='listed', nullable=False),
    sa.Column('runtime_type', sa.Text(), nullable=False),
    sa.Column('runtime_arn', sa.Text(), nullable=True),
    sa.Column('runtime_qualifier', sa.Text(), nullable=True),
    sa.Column('runtime_endpoint', sa.Text(), nullable=True),
    sa.Column('framework', sa.Text(), nullable=True),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('disclaimer', sa.Text(), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('starters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(runtime_type = 'agentcore' AND runtime_arn IS NOT NULL) OR (runtime_type = 'http' AND runtime_endpoint IS NOT NULL)", name=op.f('ck_agents_runtime_target')),
    sa.CheckConstraint("color IN ('red', 'blue', 'green', 'purple', 'amber', 'grey')", name=op.f('ck_agents_color')),
    sa.CheckConstraint("runtime_type IN ('agentcore', 'http')", name=op.f('ck_agents_runtime_type')),
    sa.CheckConstraint("stage IN ('beta', 'stable')", name=op.f('ck_agents_stage')),
    sa.CheckConstraint("status IN ('online', 'degraded', 'offline')", name=op.f('ck_agents_status')),
    sa.CheckConstraint("visibility IN ('listed', 'hidden')", name=op.f('ck_agents_visibility')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents')),
    sa.UniqueConstraint('slug', name=op.f('uq_agents_slug'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('google_sub', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='invited', nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status = 'invited' OR google_sub IS NOT NULL", name=op.f('ck_users_active_has_sub')),
    sa.CheckConstraint("status IN ('invited', 'active', 'disabled')", name=op.f('ck_users_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('google_sub', name=op.f('uq_users_google_sub'))
    )
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('title_source', sa.Text(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("title_source IN ('auto', 'user')", name=op.f('ck_sessions_title_source')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_sessions_agent_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('id', 'user_id', name=op.f('uq_sessions_id_user_id'))
    )
    op.create_index(op.f('ix_sessions_agent_id'), 'sessions', ['agent_id'], unique=False)
    op.create_index('ix_sessions_archived', 'sessions', ['user_id', sa.literal_column('archived_at DESC')], unique=False, postgresql_where=sa.text('archived_at IS NOT NULL AND deleted_at IS NULL'))
    op.create_index('ix_sessions_purge', 'sessions', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index('ix_sessions_recent', 'sessions', ['user_id', sa.literal_column('last_message_at DESC')], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_sessions_sidebar', 'sessions', ['user_id', 'agent_id', sa.literal_column('last_message_at DESC')], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND archived_at IS NULL'))
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='complete', nullable=False),
    sa.Column('blocks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('client_message_id', sa.UUID(), nullable=True),
    sa.Column('reply_to_id', sa.UUID(), nullable=True),
    sa.Column('agent_version', sa.Text(), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(search_text, ''))", persisted=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(blocks) = 'array'", name=op.f('ck_messages_blocks_is_array')),
    sa.CheckConstraint("role = 'assistant' OR status = 'complete'", name=op.f('ck_messages_user_message_complete')),
    sa.CheckConstraint("role IN ('user', 'assistant')", name=op.f('ck_messages_role')),
    sa.CheckConstraint("status IN ('streaming', 'complete', 'stopped', 'failed', 'interrupted')", name=op.f('ck_messages_status')),
    sa.ForeignKeyConstraint(['reply_to_id'], ['messages.id'], name=op.f('fk_messages_reply_to_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id', 'user_id'], ['sessions.id', 'sessions.user_id'], name=op.f('fk_messages_session_id_user_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_messages_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('id', 'user_id', name=op.f('uq_messages_id_user_id')),
    sa.UniqueConstraint('session_id', 'client_message_id', name=op.f('uq_messages_session_id_client_message_id')),
    sa.UniqueConstraint('session_id', 'seq', name=op.f('uq_messages_session_id_seq'))
    )
    op.create_index(op.f('ix_messages_reply_to_id'), 'messages', ['reply_to_id'], unique=False)
    op.create_index('ix_messages_search', 'messages', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('uq_messages_streaming_per_session', 'messages', ['session_id'], unique=True, postgresql_where=sa.text("status = 'streaming'"))
    op.create_table('share_links',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('up_to_seq', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(slug) >= 22', name=op.f('ck_share_links_slug_length')),
    sa.ForeignKeyConstraint(['session_id', 'user_id'], ['sessions.id', 'sessions.user_id'], name=op.f('fk_share_links_session_id_user_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_share_links_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_links')),
    sa.UniqueConstraint('slug', name=op.f('uq_share_links_slug'))
    )
    op.create_index('ix_share_links_active', 'share_links', ['session_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_message_id', sa.UUID(), nullable=True),
    sa.Column('artifact_key', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('current_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('document', 'code', 'html', 'table')", name=op.f('ck_artifacts_type')),
    sa.ForeignKeyConstraint(['created_message_id'], ['messages.id'], name=op.f('fk_artifacts_created_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id', 'user_id'], ['sessions.id', 'sessions.user_id'], name=op.f('fk_artifacts_session_id_user_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_artifacts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts')),
    sa.UniqueConstraint('session_id', 'artifact_key', name=op.f('uq_artifacts_session_id_artifact_key'))
    )
    op.create_index('ix_artifacts_library', 'artifacts', ['user_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_index(op.f('ix_artifacts_user_id_type'), 'artifacts', ['user_id', 'type'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('reasons', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating IN (-1, 1)', name=op.f('ck_feedback_rating')),
    sa.ForeignKeyConstraint(['message_id', 'user_id'], ['messages.id', 'messages.user_id'], name=op.f('fk_feedback_message_id_user_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_feedback_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback')),
    sa.UniqueConstraint('message_id', 'user_id', name=op.f('uq_feedback_message_id_user_id'))
    )
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.LargeBinary(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("purpose IN ('upload', 'artifact', 'thumbnail', 'export', 'tool_output')", name=op.f('ck_files_purpose')),
    sa.CheckConstraint("status IN ('pending', 'uploaded', 'failed')", name=op.f('ck_files_status')),
    sa.ForeignKeyConstraint(['message_id', 'user_id'], ['messages.id', 'messages.user_id'], name=op.f('fk_files_message_id_user_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id', 'user_id'], ['sessions.id', 'sessions.user_id'], name=op.f('fk_files_session_id_user_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_files_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files')),
    sa.UniqueConstraint('s3_key', name=op.f('uq_files_s3_key'))
    )
    op.create_index(op.f('ix_files_message_id'), 'files', ['message_id'], unique=False)
    op.create_index(op.f('ix_files_session_id'), 'files', ['session_id'], unique=False)
    op.create_index('ix_files_unattached', 'files', ['created_at'], unique=False, postgresql_where=sa.text('message_id IS NULL'))
    op.create_table('artifact_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default='streaming', nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('thumbnail_file_id', sa.UUID(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status = 'streaming' OR content IS NOT NULL OR file_id IS NOT NULL", name=op.f('ck_artifact_versions_has_body')),
    sa.CheckConstraint("status IN ('streaming', 'complete', 'incomplete')", name=op.f('ck_artifact_versions_status')),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_artifact_versions_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_artifact_versions_file_id_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_artifact_versions_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thumbnail_file_id'], ['files.id'], name=op.f('fk_artifact_versions_thumbnail_file_id_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_artifact_versions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifact_versions')),
    sa.UniqueConstraint('artifact_id', 'version', name=op.f('uq_artifact_versions_artifact_id_version'))
    )
    op.create_table('tool_calls',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tool_use_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='running', nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_file_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('running', 'awaiting_approval', 'succeeded', 'failed', 'denied', 'cancelled')", name=op.f('ck_tool_calls_status')),
    sa.ForeignKeyConstraint(['message_id', 'user_id'], ['messages.id', 'messages.user_id'], name=op.f('fk_tool_calls_message_id_user_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['output_file_id'], ['files.id'], name=op.f('fk_tool_calls_output_file_id_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id', 'user_id'], ['sessions.id', 'sessions.user_id'], name=op.f('fk_tool_calls_session_id_user_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tool_calls_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_calls')),
    sa.UniqueConstraint('message_id', 'tool_use_id', name=op.f('uq_tool_calls_message_id_tool_use_id'))
    )
    op.create_index(op.f('ix_tool_calls_session_id'), 'tool_calls', ['session_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tool_call_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.Text(), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('display', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decided_user_agent', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status IN ('pending', 'expired', 'cancelled')) = (decided_at IS NULL)", name=op.f('ck_approval_requests_decided_at_matches')),
    sa.CheckConstraint("executed_at IS NULL OR status = 'approved'", name=op.f('ck_approval_requests_execute_only_approved')),
    sa.CheckConstraint("status IN ('pending', 'approved', 'denied', 'expired', 'cancelled')", name=op.f('ck_approval_requests_status')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_approval_requests_agent_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['message_id', 'user_id'], ['messages.id', 'messages.user_id'], name=op.f('fk_approval_requests_message_id_user_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id', 'user_id'], ['sessions.id', 'sessions.user_id'], name=op.f('fk_approval_requests_session_id_user_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_call_id'], ['tool_calls.id'], name=op.f('fk_approval_requests_tool_call_id_tool_calls'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_approval_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests')),
    sa.UniqueConstraint('tool_call_id', name=op.f('uq_approval_requests_tool_call_id'))
    )
    op.create_index('ix_approvals_expiry', 'approval_requests', ['expires_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('ix_approvals_pending', 'approval_requests', ['user_id', 'session_id'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_approvals_pending', table_name='approval_requests', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('ix_approvals_expiry', table_name='approval_requests', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_tool_calls_session_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_table('artifact_versions')
    op.drop_index('ix_files_unattached', table_name='files', postgresql_where=sa.text('message_id IS NULL'))
    op.drop_index(op.f('ix_files_session_id'), table_name='files')
    op.drop_index(op.f('ix_files_message_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_artifacts_user_id_type'), table_name='artifacts')
    op.drop_index('ix_artifacts_library', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('ix_share_links_active', table_name='share_links', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('share_links')
    op.drop_index('uq_messages_streaming_per_session', table_name='messages', postgresql_where=sa.text("status = 'streaming'"))
    op.drop_index('ix_messages_search', table_name='messages', postgresql_using='gin')
    op.drop_index(op.f('ix_messages_reply_to_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_sessions_sidebar', table_name='sessions', postgresql_where=sa.text('deleted_at IS NULL AND archived_at IS NULL'))
    op.drop_index('ix_sessions_recent', table_name='sessions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_sessions_purge', table_name='sessions', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_index('ix_sessions_archived', table_name='sessions', postgresql_where=sa.text('archived_at IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index(op.f('ix_sessions_agent_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_table('agents')
    # ### end Alembic commands ###
