"""alignment review fixes
Generated by `alembic revision --autogenerate`, reviewed by hand; the status CHECK change is manual (autogenerate
doesn't detect CHECK changes). Why: alignment review (build step 4b), ARCHITECTURE D11, D19, P1, P4.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-29 14:11:34.142189
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Agent descriptor fields the screens show (#7).
    op.add_column('agents', sa.Column('tagline', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('greeting', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agents', sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agents', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))

    # Runs that survive two tasks during a deploy (B3).
    op.add_column('messages', sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True))

    # Approval pause (D1).
    op.drop_constraint(op.f('ck_messages_status'), 'messages', type_='check')
    op.create_check_constraint(
        op.f('ck_messages_status'), 'messages',
        "status IN ('streaming', 'awaiting_approval', 'complete', 'stopped', 'failed', 'interrupted')",
    )
    op.drop_index(op.f('uq_messages_streaming_per_session'), table_name='messages', postgresql_where="(status = 'streaming'::text)")
    op.create_index('uq_messages_open_reply_per_session', 'messages', ['session_id'], unique=True, postgresql_where=sa.text("status IN ('streaming', 'awaiting_approval')"))

    # Idempotent first send (B2).
    op.drop_constraint(op.f('uq_messages_session_id_client_message_id'), 'messages', type_='unique')
    op.create_unique_constraint(op.f('uq_messages_user_id_client_message_id'), 'messages', ['user_id', 'client_message_id'])


def downgrade() -> None:
    op.drop_constraint(op.f('uq_messages_user_id_client_message_id'), 'messages', type_='unique')
    op.create_unique_constraint(op.f('uq_messages_session_id_client_message_id'), 'messages', ['session_id', 'client_message_id'])

    op.drop_index('uq_messages_open_reply_per_session', table_name='messages', postgresql_where=sa.text("status IN ('streaming', 'awaiting_approval')"))
    op.create_index(op.f('uq_messages_streaming_per_session'), 'messages', ['session_id'], unique=True, postgresql_where=sa.text("status = 'streaming'"))
    op.execute("UPDATE messages SET status = 'complete' WHERE status = 'awaiting_approval'")
    op.drop_constraint(op.f('ck_messages_status'), 'messages', type_='check')
    op.create_check_constraint(
        op.f('ck_messages_status'), 'messages',
        "status IN ('streaming', 'complete', 'stopped', 'failed', 'interrupted')",
    )

    op.drop_column('messages', 'cancel_requested_at')
    op.drop_column('messages', 'heartbeat_at')
    op.drop_column('agents', 'details')
    op.drop_column('agents', 'deployed_at')
    op.drop_column('agents', 'status_changed_at')
    op.drop_column('agents', 'greeting')
    op.drop_column('agents', 'tagline')
